---
title: "An ode to the SUV"
date: 2026-02-14
format: html
categories: [cars, poem, jokes]
---

In the spirit of Valentine's Day, I write a poem about how much I ~~adore~~ abhor the SUV.

i luv driving in my suv\
it’s my Cinderella carriage\
it’s so vast and huge and wonderful\
it won’t fit in my garage\

i luv driving in my suv\
i’m off-road all the time\
from kensington to richmond park\
the bus is just a crime\

I luv driving in my suv\
i’m way up high, so tall\
there’s kiddies playing in the way?\
can’t seem them, they’re too small!\

i luv driving in my suv\
spewing clouds of CO2\
cant find an XL parking space\
i’ll have to straddle two\

i luv driving in my suv\
its size is unimpeded\
perfect for these city streets\
where more fatal strikes are needed\

i luv driving in my suv\
it makes me look so wealthy!\
its called “conspicuous consumption”\
it’s shows my self esteem is healthy\

i luv driving in my suv\
i honk at cyclists loads!\
though please ignore the fuel efficiency\
or rate of wear to roads\

i luv driving in my suv\
i’d even drive electric\
so long as i can cruise and kill\
and keep my city streets dyspeptic\
