---
title: "Who's lane is it anyway?"
date: 2026-05-22
format: html
categories: [cars, carbrain]
draft: true
---
Whenever I cycle in to work, I find myself yelling or at least thinking loudly at least once:

GET OUT THE EFFING ROAD. THIS ISN’T A CROSSING. LOOK WHERE YOU’RE GOING.

There’s every chance that I have a particularly acute case of road rage, and this is probably definitely the case. But hopefully I will also be able to convincingly argue that this widespread animosity between cyclists and pedestrians is actually an inevitable symptom of car culture.

In the early 20th century, streets were not the rigidly enforced concrete arenas we see today. Streets were informal crowded public spaces full of people, horses, bicycles, trams, motorbuses and a few spluttering motorcars:

- [video]

This may not be your idea of a perfect city street, and it certainly had its problems, but it can’t be denied that these streets operated at a human scale, at human(ish) speeds, for human people. Everyone was welcome.

Then, at the turn of the 20th century, the car came onto the scene (not without some pushback) and split people into those with cars and those without. bringing along major increases in road deaths and injury thanks to their speed, the lack of a formalised traffic rules (the Highway Code came into effect in 1931), and the fact that cars are *enormous metal boxes*. Suddenly roads became places where humans were not welcome, at risk of death. 

As pedestrians and cyclists alike were ousted from the streets, only the hardy are left - cyclists who can keep better pace with cars, who can withstand being cramped into the left side of the lane, who can stomach close passes. This makes cycling in cities a generally stressful experience, pedalling as fast as you can while constantly fearing being clipped. In this high-speed high-stakes context, it’s understandably frustrating when someone staring at their phone fails to look before they step out in the road. 

But however fast we pedal we will never be cars. We continue to be denied [our right to be use public street space](https://www.cyclingweekly.com/news/one-in-three-drivers-think-cyclists-should-be-banned-from-public-roads) and even our right to be [percieved as humans](https://www.sciencedirect.com/science/article/abs/pii/S136984781830859). The auto lobby has succeeded in persuading the public and the policymakers that it is the everyone else who is in the way, and that roads are the domain of cars only. The most famous example of this is the introduction of the concept of “jaywalking” in 1925 which frames those who walk on a street outside of designated crossing areas as naïve and dangerous, and even criminal in some places. [A horrifying recent example](https://abcnews.go.com/US/parents-charged-manslaughter-boy-struck-car-gastonia-north-carolina/story?id=122500748) of this completely skewed perception of fault and blame can be seen in North Carolina where parents have been charged with manslaughter after their child was killed by a car in the street. Now the uniquity of cars means it’s possible to never interact with people who are different from you on the street or on the bus, you’re safely insulated from the world and other people’s lives. Cars helped to breed capitalism’s ultimate individualistic (neo-)liberal “us and them” society.

And so this rage and rigidity of who can be on which part of the street when comes directly from a car-centric system. We are perpetuating the trauma: ignore bikes’ right to the street and bikes ignore pedestrians’ rights. It could almost be seen as a form of Stockholm Syndrome, supporting the motorist-friendly rules that erode the rights of vulnerable active travellers and make our own commutes a dangerous hellscape. I see cyclists cutting off pedestrians crossing lawfully at a zebra or pelican crossing, making it unsafe and unpleasant for pedestrians in their final remaining haven of street space: the temporary green man or the occasional 2m striped patch. Even cyclists get angry at fellow cyclists for [“making drivers angry”](https://www.spectator.co.uk/article/why-do-cyclists-insist-on-making-drivers-furious/). How did we get so sucked in to car-brain? 

Illustration by Karl Jilg, Swedish Road Administration. From https://www.pps.org/article/what-is-shared-space.

Cycles, scooters, pedestrians alike are all vulnerable non-car travellers, and will always have more in common with each other than with cars. Whether we travel without a car always or sometimes, because of need or preference, for financial, environmental, practical, or even aesthetic reasons, let’s stand in solidarity and respect each other on the roads, even if the cars won’t.