---
title: "Driving free: a short story"
date: 2026-07-16
format: html
categories: [cars, carbrain]
draft: false 
---

I climb into my car in the enormous grey office car park as the clock hits 7.51pm. God, I hate it in there – being in my little cubicle all day, confined in a box, surrounded by paperwork and sexist managers. It’s just senseless pen-pushing and box-ticking bureaucracy, but somehow administered in such a strict hierarchy of control and painstaking scrutiny. It’s suffocating.

I’m so relieved to be out of there and in my car, my own little pocket of freedom and wildness. I like to imagine I’m cruising through the countryside, like in those old movies, with none of this day-to-day bullshit to deal with. Just me and the road and all of the world at my fingertips. I’m free, I’m alone, and I answer to nobody.

*THUNK.*

That goddamn pothole on Clementine Avenue. How have they not fixed that yet? It’s been weeks, I swear. Someone should sort that out before there’s an accident. I worry the jolt from the pothole encounter must have shaken something loose, as a tinny rattling starts from the front of the car. Then I remember I left some coins in the passenger seat door pocket and they must be rattling around in there. Thank god – I have no idea how cars really work and I hate having to deal with Andrea at the shop. She’s always having a go that I’m not self-sufficient and can’t even change a tyre and that’s not very feminist of me or whatever. I've got better things to do than figure out how all those pipes and engines work. That’s Andrea’s job, and I pay her to do it.

Anyways – tonight is the night! Daphne has organized for all of us to go dancing at this new venue on the outskirts of town for her 30th. I’m really excited. It’s been ages since I went dancing and I’ve heard some good things about this venue. They apparently serve every cocktail under the sun, but with a silly animal-themed name like Meowtini or something. Daphne loves that novelty stuff. I’m heading there straight from work so I try to get into the party spirit by cranking up the radio and reach over to get my rave shades out of the glovebox. My MOT reminder letter falls out of the compartment where I stashed it the other day. Shit. Looks like I’m going to have to deal with Andrea next week anyways. To be honest, I can’t believe my ancient janky car hasn’t failed on the environmental side of things yet, given the smoky fumes that come out the back sometimes. Maybe this is the year I’ll have to upgrade. I sigh, wishing that life didn’t have to be so full of endless admin.

I hit the accelerator and open the window a crack to feel the wind in my hair and relax into the drive as I cruise on the dual carriageway. There’s a flash as I pass the speed camera. I look down at my speedometer and it says 75mph. GODDAMIT. Those bright yellow boxy bastards. Ughh, ANPR can eat my shorts. I hate this surveillance nonsense, like, just chill already. It’s not like an extra 5mph is hurting anyone. I reluctantly bring my speed down to just under 70mph, feeling like I have had my wings clipped or a tight leash clamped around my neck.

Still, it’s better than taking the bus. At least I’m not waiting at that stop for 20 minutes, not knowing if or when that hulking green rectangle will pull up. I know that I’ll be at the venue in exactly – I check GoogleMaps for the ETA – 57 minutes. Wait, what?? I swear it said less than 30 minutes last time I looked. I noticed that the route marker on the map had turned red for the next mile or so and as I reached the top of the shallow hill in the road I’d been climbing, an ocean of static car backsides emerged, each jeering at me with their red twinkling eyes through the dusk. I was already running late but this extra delay meant Daphne would be mad.

"Hey, Siri. Text Daphne saying "Hey Daphne so sorry I’m gonna be about half an hour late cos of mega traffic. I’ll buy you a drink to make up for it! Hyped to boogie with you soon babe"".

Just over half an hour later, I emerge out of the congestion and the road speed picks up again. I see on the hard shoulder the wreckage of two cars – their collision must have caused the traffic. Their drivers were long gone, but the physical damage was clear. I hope they’re all okay. People should be more careful, really. I finally make it to the venue and start looking for somewhere to park. There’s no designated car park, so I stalk the side roads for about 15 minutes until I find a space between two driveways. It’s a narrow street so I squeeze partly onto the pavement, hoping that the traffic wardens won’t be coming round here on a Friday night. I pay at the machine – they’ve not upgraded to the app system here it seems – and it comes to nearly a tenner. Absolute rip-off for a dark street with a dusting of what looks like the glass of car windows all across the pavement. I double check that I locked the car and power walk in to the venue.

"Hey girl!! Omg happy birthday!!! Sorry I’m so late, traffic and all, you know how it is. Lemme get you a drink – what you having?" I greet Daphne. She squeezes me and, after pretending to scold me for my lateness, places her order. I leave her to the dancefloor and head over to the bar.

"Hey man, I’ll have one um… Kitty Colada and one diet coke please."

"ID?" The bartender asked. I’m always flattered to be ID-ed in my late twenties.

"Yeah, course. Here you go." I hand over my driving license. The bartender examines it for longer than he should. I notice his name is Josh on his nametag.

"It’s a bad picture haha, the lighting is terrible," I joke self-consciously.

"No no, it’s not that! I think you live on the same street as my Nan is all! And your birthday is like 2 days off from mine! Small world hey!" Josh smiles disarmingly but I’m annoyed.

I can’t tell if this is an extremely poor attempt at flirting with me but regardless, it was creepy. We all know the unspoken agreement that you just check I’m over 18 and ignore all the actual personal information on there. Just because the DVLA needs all my details, it doesn’t mean you should know it, Josh. I snatched my ID back and shut him down as quickly as I could. "Hah, yeah, small world. Bye."

I skip back to Daphne and the gang. "What, you just got a diet coke? C’mon the cocktails are so good here, and we’re celebrating," Daphne whines jokingly.

"Yeah, but I’m driving remember? Can’t drink and drive you all home can I!"

"Hey don’t blame me!" Chimes in one of Daphne’s work friends. "I’m catching the bus home!"

Daphne and I meet eyes and laugh as if to say "This guy". He’s the worst. We dance to the cheesy pop hits until the early hours when Daphne decides she’s finally ready for some chips and bed. I drive her and a couple others to their doors and make sure they get home okay. I'm annoyed that I’m the designated driver, but I guess it’s my turn.

I finally return home. I’m absolutely exhausted yet totally wired. That was a lot of time behind the wheel; I always find driving at night stressful, especially with 3 drunk friends and 3 ketchup-laden boxes of chips whirling around. It’s been a long day. I enter my front door and notice a pile of post on the floor. It’s mostly junk but amongst the takeout menus and local political canvassing, I spot a letter from my car insurance company. I wince, remembering the yellow camera’s flash and the inevitable increase of my premium.

Screw it, I’m not dealing with that tonight. I’m going to go for a walk to clear my head and decompress before bed.

I turn 180 degrees back into the cool night air. As I walk along my street, I notice that each house has at least one metal cubicle parked up outside. Looks like everyone here has their own pocket of freedom to go where they want, when they want too. If they can afford it. If they follow the rules correctly, if the lights and signs and roads are maintained properly, if they have somewhere to park at the other end.

I pick my way between the cars parked on the pavement, barely able to navigate through them, wondering how Mrs Halliday at 42 gets through here with her Zimmer frame. I can hear the revving of a sports car racing down the main road the next street over, and after a couple of seconds the smell of toxic exhaust fumes fills my nostrils. They’re definitely not passing their next MOT I chuckle to myself.

I cross the road to where the footpath towards the common begins.

I emerge from the blue-white LED-lit path into the common as the sun’s warm glow begins to fill the sky and walk meanderingly through the trees, across the grassy lawns. The birds are beginning their morning song, and the planted flowerbeds sparkle pink-red in the dew. I take a deep breath. I am not registered, taxed, insured, or restricted to a painted lane.

For the first time all day I actually feel free.
