---
title: "Plane Wrong: reflections on academic air travel"
format: html
---

As I write this, I’m sitting in my 5th-floor hotel room in the 11th arrondissement of Paris. I’ve just completed the first leg of my rail trip to Portugal for the European Transport Conference where I’m presenting my [work on quantifying transport flexibility](https://mjmwood.github.io/presentations.html) after which I’ll travel by rail again to Brussels for the Third International Conference on Clean Mobility and Energy. Both conferences back-to-back by rail take the best part of 2 weeks, and adding on a personal trip and another academic visit to Switzerland takes me up to 3 weeks of inter-European rail fun.

When I tell people about my plans to travel to these events by rail, I usually get one of two responses:

1.  Cool! That’s really exciting!

2.  Why the heck don’t you just fly?

Response 2 is, honestly, the more immediately logical response. Instead of a quick 2-3 hour flight London-Porto, the rail journey spans three days with overnight stops in Paris and Madrid, totalling \~20 hours in a train (or coach). One way, it costs \~4x more than flying (including accommodation en route – likely an underestimate as this was evaluated using last-minute flight prices)^1^.

My reason for travelling by rail is the environment. Flying is one of the most carbon-intensive activities a person can undertake; one-way London-Porto emits \~260 kgCO2e which is approximately equal to the average annual emissions for a person living in Afghanistan \[1, 2\]. On the other hand, emissions from rail are vanishingly small. Most rail in Europe (including the high-speed lines that span London - Paris - Barcelona - Madrid) are fully electrified with much of the energy sourced from renewables. As a result, a quick back-of-the-envelope calculation estimates that the same trip by rail and coach emits approximately 23kgCO2e - a whopping reduction of over 90%^2^!

As a PhD student researching sustainable transport, flying to two conferences that focus on sustainable transport would generate simply unfathomable levels of irony.

Nevertheless, despite having the willingness, time, and an earmarked conference fund that I had saved over the past 3 years for this express purpose, I found it surprisingly difficult to have the travel funding approved. Since I was not travelling by the “conventional” route I was asked to provide a written statement justifying my request. In researching UCL policy to provide my justifications, I learned that UCL actually has a series of targets and schemes pointing exactly towards flight-free travel (though not in so many words). Among targets to be net zero emissions (scopes 1, 2, and 3 – including academic travel) by 2040, specific policies include:

-   Requirements to "seek low carbon alternatives" to travel (Travel Policy, §2.3.1).

-   Hierarchy of travel options ranks the airplane as the least preferred mode of transport, below rail and car (Travel Policy, §2.3.2).

-   Staff and students "should always try to select the most carbon-efficient way of reaching a destination," and this "may not necessarily be the cheapest" (Travel Policy, §3, para. 3).

-   Staff should select the most sustainable option "even if this is not always the cheapest option" (Expenses Policy, §3.5.1).

These policies have earned UCL the UK’s #1 most sustainable university and #3 in the world \[3\]. Impressive, but surely meaningless if not implemented. In the year 2024-2025, academic travel accounted for 14% of all scope 1, 2, and 3 emissions from UCL remaining one of the largest remaining sources of carbon, after natural gas use (!) and purchased goods and services \[4\]. I’m shocked, therefore, that more concrete schemes are not in place to encourage low-carbon academic travel, especially within Europe. While London-Porto by rail is admittedly on the more ‘adventurous’ end of rail travel, and thus may be less obviously possible flight-free, there is equally no formal guardrail to stop someone travelling by air to Brussels (a direct 2-hour Eurostar train). A policy that employs a graduated system, based on travel time and carbon saving for example, could be implemented to ensure air travel is limited to only where strictly necessary^3^. Support with itinerary planning should be offered to reduce the large and often overwhelming mental load that complex multi-leg journeys bring. Rather than needing to provide justification for non-air travel, the default should be assumed rail and special permission sought for air travel instead.

I fully acknowledge that most individuals are not able to quadruple the cost of their trips or take several extra days of holiday from work; this article is absolutely not aimed at any individuals who fly to their holiday destinations. It is well established that the current political, financial, and regulatory landscape renders personal sustainable travel a luxury \[5\]. However, within academia, universities should be setting an example and pushing against air travel more strongly. There is rich precedent for universities leading change throughout history, from students leading protests for social change (from May \`68 to protests against the genocide in Gaza) to institutional fossil fuel divestment \[6\], and they should continue to use their influence, privilege, and money to instigate positive change including the de-normalization of frequent short-haul air travel.

[Footnotes]{.underline}

^1^ The difference could be up to 7x if taking the most budget flight I could find. The entire round trip is slightly more complicated as it compares two separate return flights to each conference while the rail route comprises one long trip.

^2^ My basic calculations to reach these values are available on request

^3^ See references 7 - 10 for further discussions over whether academic air travel and whether it truly is essential

[References]{.underline}

\[1\] ClarityGo carbon estimate for my specific trip. ClarityGo is the travel booking application used by UCL for academic travel

\[2\] Global Carbon Budget (2025); Population based on various sources (2024) – with major processing by Our World in Data. “CO₂ emissions per capita” \[dataset\]. Global Carbon Project, “Global Carbon Budget v15”; Various sources, “Population” \[original data\]. Retrieved September 7, 2026 from <https://archive.ourworldindata.org/20260807-075129/grapher/co-emissions-per-capita.html> (archived on August 7, 2026).

\[3\] UCL News (2025). 'UCL ranks 1st in the UK and 3rd globally in QS Sustainability Rankings', 18 November. Available at: <https://www.ucl.ac.uk/news/2025/nov/ucl-ranks-1st-uk-and-3rd-globally-qs-sustainability-rankings>

\[4\] UCL (2025). *Annual Sustainability Report 2024–2025*. Available at: <https://www.ucl.ac.uk/sustainable/sites/sustainable/files/annual_sustainability_report_undesigned_version_2024-25.pdf>

\[5\] Zamora, J. (2025). '3 Reasons why flights are far cheaper than trains and why that has to change'. *Greenpeace International*, 27 August. Available at: <https://www.greenpeace.org/international/story/78154/3-reasons-why-flights-are-far-cheaper-than-trains-and-why-that-has-to-change/>

\[6\] Ellis, R. (2024). 'Global university fossil fuel divestment "nearing tipping point"'. *Times Higher Education*, 12 June. Available at: <https://www.timeshighereducation.com/depth/global-university-fossil-fuel-divestment-nearing-tipping-point>

\[7\] Görlinger, S., Merrem, C., Jungmann, M. *et al.* An evidence-based approach to accelerate flight reduction in academia. *npj Clim. Action* **2**, 41 (2023). <https://doi.org/10.1038/s44168-023-00069-y>

\[8\] Nevins, J., Allen, S., & Watson, M. (2021). A path to decolonization? Reducing air travel and resource consumption in higher education. *Travel Behaviour and Society*, *26*, 231–239. <https://doi.org/>[10.1016/j.tbs.2021.09.012](https://doi.org/10.1016/j.tbs.2021.09.012)

\[9\] Büchs, M. (2019). 'University sector must tackle air travel emissions'. *The Conversation*, 2 July. Available at: <https://theconversation.com/university-sector-must-tackle-air-travel-emissions-118929>

\[10\] de Vos, J., Hopkins, D., Hickman, R., & Schwanen, T. (2024). Tackling the academic air travel dependency. An analysis of the (in)consistency between academics’ travel behaviour and their attitudes. *Global Environmental Change*, *88*, 102908. <https://doi.org/10.1016/j.gloenvcha.2024.102908>
