---
title: "No way(mo) out"
date: 2026-05-30
format: html
categories: [cars, AVs, carbrain]
draft: false 
---

Last week, the [UK Government opened applications](https://www.gov.uk/government/news/passengers-one-step-closer-to-booking-taxi-and-bus-style-self-driving-vehicles) for companies to begin operating autonomous taxi, bus, and ride-hailing services, with a view that customers will be able to begin using the services by the end of this year. Waymo’s distinctive white vehicles have already been prowling the streets of London for several months as they map its streets, recently even without their human safety drivers, as they map the streets. While there’s a lot of understandable hype building around these futuristic cars, I don't think they're the transportation panacea people might be expecting.

## Road safety

Road safety is one of the most prominently cited benefits of autonomous vehicles (AVs). [According to the Department for Transport,](https://www.gov.uk/government/news/self-driving-vehicles-set-to-be-on-roads-by-2026-as-automated-vehicles-act-becomes-law) 88% of all collisions are caused by human error, including “drink driving, speeding, tiredness and inattention”. It stands to reason that we could therefore eliminate the vast majority of road collisions by using AVs. Moreover, [Waymo's own safety research](https://waymo.com/safety/impact/), based on trials in the USA, show that using their AVs leads to a 92% decrease in collisions and a 82% decrease in serious injury caused by collisions.

These statistics are fantastic, and it cannot be denied that reducing road collisions is objectively a good thing. However, AVs are not the only way to achieve this. [It has been shown that](https://researchbriefings.files.parliament.uk/documents/POST-PB-0065/POST-PB-0065.pdf) reducing speed limits to 20mph significantly reduces rates of collisions and serious injury from collisions with studies reporting up to 20-60% reductions in injuries and fatalities across the UK. Moreover, reducing the bonnet height of cars is essential for reducing fatal collisions: [one study found that](https://www.transportenvironment.org/articles/new-car-bonnets-becoming-half-centimetre-higher-every-year-study) a 10cm increase in bonnet height increases the risk of death to pedestrians and cyclists by 27%. With a car population that has grown in height by over 16cm since 2010, such that children as old as 9 are invisible from the driver's seat, we should be urgently passing regulations to limit vehicle bonnet height.

Ignoring these easy wins while embracing the hype of novelty robotaxis seems short sighted and symptomatic of deep-set car-brain. Reducing speeds and reducing bonnet heights are fast, simple, and sure-fire ways to reduce road collisions, and reducing the number of cars on the roads would go a step further again. After all, 100% of car collisions involve cars.

## Sustainability

[Waymo’s website](https://waymo.com/waymo-in-uk/) also discusses the green credentials of electric AVs. Many argue that, since these electric vehicles are a shared fleet, they will be able to replace private car journeys and take other cars off the roads. This echoes remarkably well what was said about Uber coming to our streets several years ago. Yet, it has been shown that Uber has had no such effect, and has in fact [increased vehicle miles travelled](https://www.sfcta.org/projects/tncs-and-congestion) and even [contributed greater emissions per trip overall](https://pubs.acs.org/doi/full/10.1021/acs.est.1c01641) as drivers circle cities waiting for their next fare. While Waymo have [addressed this specifically](https://www.mylondon.news/news/transport/waymo-driverless-taxi-trial-london-33901846), stating that they “limit empty miles” by ensuring unused vehicles will be directed to park or return to the distribution depot, there’s no convincing evidence that these measures will be effective (and where is there to park in central London!?). Though these new AVs are electric - thus definitively "sustainable" according to Waymo - these additional miles are hardly eco-friendly; all vehicles generate [pollution from tires and brake pads](https://www.theguardian.com/environment/2025/feb/14/brake-pad-dust-toxic-exhaust-emissions), and heavier EVs are in fact the worst offenders.

Moreover, the introduction of AVs may deter cyclists from using our streets. Cyclists are already vulnerable road users, with [nearly half of cyclists feeling unsafe on the roads of London today](https://www.standard.co.uk/news/transport/cyclists-safe-london-roads-tfl-b1272244.html), and concerns are being raised that they may be at greater risk with AVs on the roads. In particular, there have been reports of Waymo vehicles stopping and picking up passengers in bike lanes (as well as [flagrantly breaking road rules](https://www.theguardian.com/technology/2025/sep/29/waymo-illegal-u-turn-driverless-car)). In 2026, Waymo allegedly announced that expecting their cars to respect cycle lanes was [“too high a bar”](https://road.cc/news/driverless-taxis-veering-into-cycle-lanes-normal-practice-says-waymo).

Surely, then, a better transport solution would reduce mileage, encourage cycling, and reduce pollution. In practice, this looks like fewer cars and a system oriented towards active travel and (electric) public transport instead; more cars cannot be the answer.

## Traffic efficiency

Similarly, we are promised that autonomous fleets will improve traffic efficiency by reducing unnecessary congestion. This will be achieved in several ways, such as by reducing phantom traffic caused by human error or through connected vehicles communicating with each other in real-time to optimise traffic flow.

These positive effects on congestion of (connected) AVs have been studied widely and are well-documented (see [here](https://www.sciencedirect.com/science/article/pii/S0378437123010099) and [here](https://link.springer.com/article/10.1007/s40534-016-0117-3) for examples). But, aside from the afore-mentioned empty miles issue, there is potential for (short-term) congestion increase due to induced demand (similar to what is [a well-observed phenomenon with road widening](https://www.wired.com/2014/06/wuwt-traffic-induced-demand/)). While some argue this temporary congestion increase will eventually subside as we ~~magically overcome our love of private vehicles and~~ shift to an entirely shared fleet of cars, I think we’re again fundamentally looking to solve the wrong problem. Instead of asking how we can reduce congestion *given the transport system stays the same*, we should be asking how can we reduce congestion *altogether*. At the end of the day, congestion consists of vehicles (you’re not IN traffic, you ARE traffic). Putting more cars on the road cannot remove congestion. Only reducing the number cars on the roads can do this.

## Accessibility

Finally, AVs are praised for their accessibility credentials, and understandably so. AVs open up car use for those who are unable to drive, for example due to disability or age. These vehicles facilitate independent travel, where previously people have had to rely heavily on insufficient public transport, asking favours from friends and family, or simply missing out.

However, as it stands, AV offerings are not designed to help the most vulnerable. A [Waymo spokesperson described](https://www.bbc.co.uk/news/articles/czej9n578k9o) fares as “competitive" but "premium”, indicating that trips in these vehicles will not be affordable for general everyday use. In the UK, the [poverty rate](https://www.jrf.org.uk/uk-poverty-statistics/disability) for disabled people is consistently higher than non-disabled people and employment rates are [significantly lower](https://www.gov.uk/government/statistics/the-employment-of-disabled-people-2025/the-employment-of-disabled-people-2025#main-points) for disabled people (52.8% compared with 82.5% for non-disabled people). With current ride-hailing app users found to be predominantly [young, employed people,](https://www.sciencedirect.com/science/article/pii/S096585641830764X) and with [middle-income young people](https://www.sciencedirect.com/science/article/pii/S2590198221001019) the most likely to adopt shared AV use, we cannot assume that using robotaxis will be of great immediate benefit to the most vulnerable. Moreover, in 2024, [only 11% of private hire vehicles](https://www.gov.uk/government/statistics/taxi-and-private-hire-vehicle-statistics-england-2024/taxi-and-private-hire-vehicle-statistics-england-2024#accessibility) in England were wheelchair accessible.

In fact, the introduction and popularisation of AVs may exclude these most vulnerable members of society even more. As [Giulio Mattioli describes](https://www.tandfonline.com/doi/full/10.1080/1523908X.2013.858592#d1e335): “the self-reinforcing cycle of car dependence results in an *increasing intensity of car deprivation for a decreasing proportion of the population”.* Those who do not drive and cannot afford a AV will be at even greater disadvantage as the ratchet of social car dependence tightens.

Waymo claiming to be a positive step for increasing transport accessibility is therefore, at best a premature and overly-optimistic assessment and at worst a co-opting of accessibility language to gain social credit. Means-tested pricing or subsidies for the most vulnerable may help to truly improve accessibility. But in general, more cars on the roads only deepens the core of the problem.

## Final thoughts

Yes, AVs are amazing technology and objectively cool. But we know better than to equate “cool” with “good”. To quote Paris Marx in his fantastic [book "Road to Nowhere"](https://roadtonowherebook.com/): “addressing the inequities and harms of our world does not require the invention of new technologies; it requires a new politics that recognises economic growth and technological innovation do not guarantee social progress”.

In summary, I think we’ve lost sight of what the true goal is. We should not be asking if AVs on the roads will improve certain elements of driving. We should be asking how to meaningfully improve people’s lives through fairer, more accessible, and more equitable transport. Improving the way we use cars is a small change of the existing system. We need a big change in the system itself.
